#apiVersion: oda.tmforum.org.oda.tmforum.org/v1beta1
#kind: MLModel
#metadata:
#  labels:
#    app.kubernetes.io/name: demo-mlmodel-operator
#    app.kubernetes.io/managed-by: kustomize
#  name: mlmodel-sample
#spec:
#  modelURL: "https://storage.googleapis.com/tfhub-modules/google/tf2-preview/mobilenet_v2/classification/4.tar.gz"
#  storageSize: "5Gi"
#  framework: "tensorflow"
#  replicas: 1
#  expose: true
#
